#!/bin/bash

#test 1 archive present
if [ ! -f ./prog1.tgz ]; then
    echo "Project archive not found in current directory. Submission will not be graded."
    exit 1
fi

gtar zxf prog1.tgz

#test 2 make 
(make) >/dev/null
made=$?
if [ "$made" -ne "0" ]; then
	echo -e "Make returned an error. Submission will not be graded."
	exit 1
fi

#test 3 f.o present
if [ ! -f ./f.o ]; then
    echo "f.o not generated by make. Submission will not be graded."
    exit 1
fi

#test 4 f.o present
if [ ! -f ./main.o ]; then
    echo "main.o not generated by make. Submission will not be graded."
    exit 1
fi

#test 5 f.o present
if [ ! -f ./a.out ]; then
    echo "a.out not generated by make. Submission will not be graded."
    exit 1
fi

echo "Submission will be graded successfully. Please be aware this does not test your submission for functionality, only that the autograder will run successfully."
