all: step1 step2 step3 step4 step5 step6 step7 step8 step9 logger
	
step1:
	gcc -std=c99 -o step1 step1.c

step2:
	gcc -std=c99 -o step2 step2.c

step3:
	gcc -std=c99 -o step3 step3.c

step4:
	gcc -std=c99 -o step4 step4.c

step5:
	gcc -std=c99 -o step5 step5.c

step6:
	gcc -std=c99 -o step6 step6.c

step7:
	gcc -std=c99 -o step7 step7.c

step8:
	gcc -std=c99 -o step8 step8.c

step9:
	gcc -std=c99 -o step9 step9.c

logger:
	gcc -std=c99 -o logger logger.c

clean:
	rm step1 step2 step3 step4 step5 step6 step7 step8 step9 logger