#!/bin/bash

#test 1 archive present
if [ ! -f ./prog2.tgz ]; then
    echo "Project archive (prog2.tgz) not found in current directory. Submission will not be graded."
    exit 1
fi

tar zxf prog2.tgz

#test 2 make 
(make) >/dev/null
made=$?
if [ "$made" -ne "0" ]; then
	echo -e "Make returned an error. Submission will not be graded. Are your source files and makefile in the current directory?"
	exit 1
fi

#test 3 ctar present
if [ ! -f ./ctar ]; then
    echo "ctar not generated by make. Submission will not be graded."
    exit 1
fi

#test 4 utar present
if [ ! -f ./utar ]; then
    echo "utar not generated by make. Submission will not be graded."
    exit 1
fi

echo "Submission will be graded successfully. Please be aware this does not test your submission for functionality, only that the autograder will run successfully."
